grammar cmd

cmd        <-  cmdbrace / cmdlist
cmdbrace   <-  " "* "(" " "* cmd " "* ")" " "*               %make_cmdbrace
cmdlist    <-  cmdop / basecmd
cmdop      <-  basecmd ("||" / "&&" / "|" / ";") cmd         %make_cmdop
basecmd    <-  " "* arg (" "+ arg)* " "*                     %make_basecmd             
arg        <-  arg_quot / arg_noquot
arg_quot   <-  ('"' [^"]* '"') / ("'" [^']* "'")             %make_arg_quot
arg_noquot <-  [^ ;|()]+                                   %make_arg_noquot

